favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5380551312118769
  brandStrength: 0.5035841
  lightness: 0.239825073396787
  brandColors:
    - '#FFFFFF'
    - '#42657A'
    - '#060404'
    - '#E91D24'
    - '#FFA4A5'
  rhythmicContrast: 0.6747377407737076
typography_spectrum: 1
layout_spectrum: 0.9516129
analytics:
  twitter: null
  google: null
  facebook: null
name: EverythingBrownsburg
